#!/bin/bash
#PBS -l nodes=1:ppn=4,walltime=00:30:00
#PBS -N app-fsl-fast

set -x
set -e

time singularity exec -e docker://brainlife/fsl:6.0.5 ./segment.sh

# clean up
if [ ! -f ./mask/mask.nii.gz ]; then
	echo "something went wrong. check logs and derivatives"
	exit 1
fi

exit 0
